### ISSUE TITLE
Implementar Blockchain

### ISSUE THREAD

**Issue by mauricio-alvarez** [maurialv1401/BlockchainAED2022-2#14]

**Comment by Alexis0816** [comment]
ClASS BLOCKCHAIN

- [ ] Atributos necesarios:

1. Longitud (size)
2. Bloque actual (Block current)
3. Bloque inicial (Block genesis)
4. Nonce (precision)
5. Transacciones (max_transactions)

- [ ] Constructores necesarios: 

1. Por defecto: se asignan los valores por defecto al Bloque genesis, al Nonce, a Transacciones ... 


![Image](https://user-images.githubusercontent.com/92095752/194804617-20ccfccb-7e12-4b08-9208-14b82809404f.jpeg)


- [ ] Métodos necesarios:

1.  Insert: inserta una transaccion que es representada por un Block en donde se tiene toda la información (utilización del merkle 
     tree para almacenar las transacciones). Además, se asignan las huellas (hash previos y actuales).
2.  Modify: Si se modifica cualquier Block, se debe minar en cadena de tal manera que se reestablecen los hashes de cada bloque 
     en la Blockchain.
3.  Print chain: Imprime toda la data contenida en una Transacción. 
4.  Size block: Retorna la cantidad de transacciones.
