### ISSUE TITLE
Implementar clase Transacciones

### ISSUE THREAD

**Issue by mauricio-alvarez** [maurialv1401/BlockchainAED2022-2#3]

**Comment by mauricio-alvarez** [comment]
Debe tener por lo menos 4 atributos:
- Emisor
- Receptor
- Cantidad / Monto
- Fecha
De ello se harán indices (arboles) para los atributos necesarios.

**Comment by nicolas-castaneda** [comment]
En lugar del tipo de dato específico que usaba Cantidad / Monto, se utiliza template para la variable data la cual representa la información que contiene una transacción.

**Comment by nicolas-castaneda** [comment]
Sobrecarga del operador << para la obtención de la información que contenga el atributo data en formato string.

**Comment by nicolas-castaneda** [comment]
# Class Transaction
- Emisor: Quien realiza la transacción
- Receptor: Recibe la transacción
- Data: Información que envía el emisor a su respectivo receptor
- Fecha: Fecha y tiempo en el que se realizo la transacción
