### ISSUE TITLE
Determinar funciones necesarias

### ISSUE THREAD

**Issue by AaronCS25** [maurialv1401/BlockchainAED2022-2#8]

**Comment by AaronCS25** [comment]
# Funciones
## Block
1. Obtener las transacciones que almacena el bloque.
2. Obtener el hash que dicho bloque almacena.
3. Obtener el hash del bloque previo al presente bloque.

## Blockchain
1. Añadir bloques a la cadena de bloques "BlockChain".
2. Modificar los bloques
3. Visualizar los datos que almacenan los bloques en la cadena de bloques.

**Comment by mauricio-alvarez** [comment]
### Merkle:

1. Hallar Merkle Path
2. Determinar pertenecia
